//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAS.BeheerderPages {
    
    
    public partial class BeheerderPage {
        
        /// <summary>
        /// DocentForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OAS.UserControls.DocentForm DocentForm;
        
        /// <summary>
        /// BeheerderForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OAS.UserControls.BeheerderForm BeheerderForm;
        
        /// <summary>
        /// StudentenForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OAS.UserControls.StudentenForm StudentenForm;
    }
}
