//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beheerder
    {
        public string Email { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsels { get; set; }
        public string Achternaam { get; set; }
        public string Wachtwoord { get; set; }
    }
}
