//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docent
    {
        public Docent()
        {
            this.Moment = new HashSet<Moment>();
            this.Klas1 = new HashSet<Klas>();
        }
    
        public string Afkorting { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsels { get; set; }
        public string Achternaam { get; set; }
        public string Email { get; set; }
        public string Telefoon1 { get; set; }
        public string Telefoon2 { get; set; }
        public string Klas { get; set; }
        public string Wachtwoord { get; set; }
        public bool Isactief { get; set; }
    
        public virtual ICollection<Moment> Moment { get; set; }
        public virtual ICollection<Klas> Klas1 { get; set; }
    }
}
