//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gesprek
    {
        public int GesprekID { get; set; }
        public int OuderID { get; set; }
        public int SubMomentID { get; set; }
        public Nullable<bool> ThuisSituatie { get; set; }
        public Nullable<bool> StudieKeuze { get; set; }
        public Nullable<bool> Voortgang { get; set; }
        public Nullable<bool> Presentatie { get; set; }
        public Nullable<bool> Motivatie { get; set; }
        public Nullable<bool> AlgemeenWelbevinden { get; set; }
        public Nullable<bool> VerwachtingsPatroon { get; set; }
        public string DocentOpmerking { get; set; }
        public string StudentOpermerking { get; set; }
        public string AfsprakenDoorverijzing { get; set; }
    
        public virtual SubMoment SubMoment { get; set; }
    }
}
