//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moment
    {
        public Moment()
        {
            this.SubMoment = new HashSet<SubMoment>();
        }
    
        public int MomentID { get; set; }
        public string DocentAfkorting { get; set; }
        public System.DateTime Datum { get; set; }
        public System.TimeSpan BeginTijd { get; set; }
        public System.TimeSpan EindTijd { get; set; }
        public System.TimeSpan Gespreksduur { get; set; }
    
        public virtual Docent Docent { get; set; }
        public virtual ICollection<SubMoment> SubMoment { get; set; }
    }
}
