//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouder
    {
        public Ouder()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int OuderID { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsels { get; set; }
        public string Achternaam { get; set; }
        public string Email { get; set; }
        public string Telefoon1 { get; set; }
        public string Telefoon2 { get; set; }
        public string Adres { get; set; }
        public string Postcode { get; set; }
        public string Woonplaats { get; set; }
        public string Wachtwoord { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
    }
}
