//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periode
    {
        public int PeriodId { get; set; }
        public System.DateTime StartDatum { get; set; }
        public System.DateTime EindDatum { get; set; }
        public bool IsActief { get; set; }
    }
}
