//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string Studentnummer { get; set; }
        public Nullable<int> KlasId { get; set; }
        public string Roepnaam { get; set; }
        public string Tussenvoegsels { get; set; }
        public string Achternaam { get; set; }
        public string Adres { get; set; }
        public string Postcode { get; set; }
        public string Woonplaats { get; set; }
        public System.DateTime GeboorteDatum { get; set; }
        public string Geslacht { get; set; }
        public string Telefoon1 { get; set; }
        public string Telefoon2 { get; set; }
        public string Opleiding { get; set; }
        public string Email { get; set; }
        public int OuderID { get; set; }
        public bool Actief { get; set; }
    
        public virtual Klas Klas { get; set; }
        public virtual Ouder Ouder { get; set; }
    }
}
