//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMoment
    {
        public SubMoment()
        {
            this.Gesprek = new HashSet<Gesprek>();
        }
    
        public int SubMomentID { get; set; }
        public int MomentID { get; set; }
        public Nullable<int> OuderID { get; set; }
        public System.TimeSpan BeginTijd { get; set; }
        public System.TimeSpan EindTijd { get; set; }
    
        public virtual ICollection<Gesprek> Gesprek { get; set; }
        public virtual Moment Moment { get; set; }
    }
}
